[package]
name = "kernel"
version = "0.1.0"
build = "build.rs"

[lib]
name = "kernel"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "0.7"
spin = "0.4"
redox_syscall = "0.1"

[dependencies.goblin]
version = "0.0.8"
default-features = false
features = ["elf32", "elf64"]

[dev-dependencies]
arch_test = { path = "arch/test" }

[target.'cfg(target_arch = "arm")'.dependencies]
arch_arm = { path = "arch/arm" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
arch_x86_64 = { path = "arch/x86_64" }

[features]
default = []
live = []
